language: python
python:
  - "3.6"
  - "3.5"
  - "2.7"
  - "3.4"
  - "3.3"
install:
    - python setup.py install
    - pip install -r requirements-tests.txt
script:
    py.test -x tests/
sudo: false
