language: python
python:
  - "2.7"
  - "pypy"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: python setup.py install && pip install -r requirements_tests.txt --use-mirrors
# command to run tests, e.g. python setup.py test
script: py.test tests
