language: python
python:
  - "3.4"
  - "2.7"
  - "pypy"
  - "3.3"
  - "2.6"
install:
    - python setup.py install
    - pip install -r requirements_tests.txt
    - pip install coveralls
script:
    py.test --cov-config .coveragerc --cov authcode tests/
