User's Guide
------------

This part of the documentation, which is mostly prose, begins with some
background information about Authcode, then focuses on step-by-step
instructions for using the library.

.. toctree::
   :maxdepth: 2

   foreword
   installation
   quickstart


Additional Notes
----------------

For the interested.

.. toctree::
   :maxdepth: 2

   security
   styleguide
   license
