Guía de usuario
--------------------------------

Esta documentación esta dividida en varias secciones.
Te recomiendo que empieces por :ref:`installation` y luego vayas a :ref:`quickstart`.
Algunos patrones comunes están descritos en la sección :ref:`patterns`.


.. toctree::
   :maxdepth: 2

   installation
   quickstart
   patterns


Notas adicionales
--------------------------------

Para los interesados.

.. toctree::
   :maxdepth: 1

   security
   license
